using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NotePaper
{
    class CategoriesLanguage
    {
        public string[] english = {
        "Reminding",
            "School",
            "Business",
            "Household Necessities",
            "Needs",
            "Wants",
            "Personal requirement",
            "Sport",
            "Trip",
            "Holiday plan",
            "Appointments",
            "Health",
            "Food",
            "Blog",
            "Special",
            "Present",
            "Birthday",
            "Holiday",
            "To Take",
            "Payments",
            "Poem",
            "Articles",
            "Technology",
            "Dreams",
            "Targets",
            "Motivation",
            "Music",
            "Nature",
            "Artificial intelligence",
            "Social",
            "Love",
            "Romance",
            "Money",
            "Friend",
            "Other"};
        public string[] russian = {
            "Напоминание",
            "Школа",
            "Бизнес",
            "Бытовые нужды",
            "Потребности",
            "Хочет",
            "Личная потребность",
            "Спорт",
            "Путешествие",
            "План отпуска",
            "Назначения",
            "Здоровье",
            "Еда",
            "Блог",
            "Специальный",
            "Подарок",
            "День рождения",
            "Праздничный день",
            "Брать",
            "Платежи",
            "Стих",
            "Статьи",
            "Технологии",
            "Мечты",
            "Цели",
            "Мотивация",
            "Музыка",
            "Природа",
            "Искусственный интеллект",
            "Социальное",
            "Любовь",
            "Романтика",
            "Деньги",
            "Друг",
            "Другой"
        };
        public string[] korea = {
            "생각나게",
            "학교",
            "사업",
            "생활 필수품",
            "필요",
            "원한다",
            "개인 요구 사항",
            "스포츠",
            "여행",
            "휴가 계획",
            "설비",
            "건강",
            "음식",
            "블로그",
            "특별한",
            "현재의",
            "생신",
            "휴일",
            "가지다",
            "결제",
            "시",
            "조항",
            "기술",
            "꿈",
            "대상",
            "동기 부여",
            "음악",
            "자연",
            "인공지능",
            "사회의",
            "애정",
            "로맨스",
            "돈",
            "친구",
            "다른"
        };
        public string[] chineese = {
            "提醒",
            "學校",
            "商業",
            "生活必需品",
            "需要",
            "想要",
            "個人要求",
            "運動",
            "旅行",
            "假期計劃",
            "約會",
            "健康",
            "食物",
            "博客",
            "特別的",
            "當下",
            "生日",
            "假期",
            "拿",
            "付款",
            "詩",
            "文章",
            "技術",
            "夢想",
            "目標",
            "動機",
            "音樂",
            "自然",
            "人工智能",
            "社會的",
            "愛",
            "浪漫",
            "錢",
            "朋友",
            "其他"
        };
        public string[] turkish = {
                              "Hatırlatma",
            "Okul",
            "İş",
            "Ev ihtiyaçları",
            "İhtiyaçlar",
            "İstekler",
            "Kişisel gereksinim",
            "Spor",
            "Seyahat",
            "Tatil planı",
            "Randevular",
            "Sağlık",
            "Yemek",
            "Blog",
            "Özel",
            "Hediye",
            "Doğum günü",
            "Bayramlar",
            "Alınacaklar",
            "Ödemeler",
            "Şiir",
            "Yazılar",
            "Teknoloji",
            "Hayaller",
            "Hedefler",
            "Motivasyon",
            "Müzik",
            "Doğa",
            "Yapay zeka",
            "Sosyal",
            "Aşk",
            "Romantizm",
            "Para",
            "Arkadaş",
            "Diğer"
        };
        public string[] Azerbaycan = {
            "Xatırlatma",
            "Məktəb",
            "Biznes",
            "Məişət ehtiyacları",
            "Ehtiyaclar",
            "İstəyir",
            "Şəxsi tələb",
            "İdman",
            "Səyahət",
            "Tətil planı",
            "Görmələr",
            "Sağlamlıq",
            "Yemək",
            "Bloq",
            "Xüsusi",
            "İndiki",
            "Ad günü",
            "Bayram",
            "Götürmək",
            "Ödənişlər",
            "Şeir",
            "Məqalələr",
            "Texnologiya",
            "Xəyallar",
            "Hədəflər",
            "Motivasiya",
            "Musiqi",
            "Təbiət",
            "Süni intellekt",
            "Sosial",
            "Sevgi",
            "Romantika",
            "Pul",
            "Dost",
            "Başqa"
        };
        public string[] German = {
            "Erinnerung",
            "Schule",
            "Geschäft",
            "Haushaltsbedarf",
            "Bedürfnisse",
            "Will",
            "Persönlicher Bedarf",
            "Sport",
            "Reise",
            "Urlaubsplan",
            "Termine",
            "Die Gesundheit",
            "Essen",
            "Blog",
            "Speziell",
            "Gegenwärtig",
            "Geburtstag",
            "Ferien",
            "Nehmen",
            "Zahlungen",
            "Gedicht",
            "Artikel",
            "Technologie",
            "Träume",
            "Ziele",
            "Motivation",
            "Musik",
            "Natur",
            "Künstliche Intelligenz",
            "Sozial",
            "Liebe",
            "Romantik",
            "Geld",
            "Freund",
            "Sonstiges"
        };
        public string[] french = {
            "Rappel",
            "École",
            "Entreprise",
            "Nécessités du ménage",
            "Besoins",
            "Veut",
            "Exigence personnelle",
            "Sport",
            "Voyage",
            "Plan vacances",
            "Nominations",
            "Santé",
            "Aliments",
            "Blog",
            "Spécial",
            "Cadeau",
            "Date d'anniversaire",
            "Vacance",
            "Prendre",
            "Paiements",
            "Poème",
            "Des articles",
            "Technologie",
            "Rêves",
            "Cibles",
            "Motivation",
            "Musique",
            "La nature",
            "Intelligence artificielle",
            "Social",
            "Aimer",
            "Romance",
            "Argent",
            "Ami",
            "Autre"
        };
        public string[] italy = {
            "Ricordando",
            "Scuola",
            "Affare",
            "Necessità domestiche",
            "Necessità",
            "Vuole",
            "Requisito personale",
            "Sport",
            "Viaggio",
            "Piano vacanze",
            "Appuntamenti",
            "Salute",
            "Cibo",
            "Blog",
            "Speciale",
            "Regalo",
            "Compleanno",
            "Vacanza",
            "Prendere",
            "Pagamenti",
            "Poesia",
            "Articoli",
            "Tecnologia",
            "Sogni",
            "Obiettivi",
            "Motivazione",
            "Musica",
            "Natura",
            "Intelligenza artificiale",
            "Sociale",
            "Amore",
            "Romanza",
            "I soldi",
            "Amico",
            "Altro"
        };
        public string[] arabic = {
            "تذكير",
            "المدرسة",
            "اعمال",
            "المستلزمات المنزلية",
            "الاحتياجات",
            "يريد",
            "المتطلبات الشخصية",
            "رياضة",
            "رحلة قصيرة",
            "خطة العطلة",
            "تعيينات",
            "صحة",
            "غذاء",
            "مقالات",
            "خاص",
            "الحالي",
            "عيد الميلاد",
            "الأعياد",
            "يأخذ",
            "المدفوعات",
            "قصيدة",
            "مقالات",
            "تكنولوجيا",
            "الخيال - الأماني",
            "الأهداف",
            "تحفيز",
            "موسيقى",
            "طبيعة سجية",
            "الذكاء الاصطناعي",
            "اجتماعي",
            "عشق",
            "رومانسي",
            "مال",
            "صديق",
            "آخر"
        };
        public string[] espanol = {
            "Recordando",
            "Escuela",
            "Negocio",
            "Necesidades del hogar",
            "Necesidades",
            "Quiere",
            "Requisito personal",
            "Deporte",
            "Viaje",
            "Plan de vacaciones",
            "Equipo",
            "Salud",
            "Alimento",
            "Blog",
            "Especial",
            "Presente",
            "Cumpleaños",
            "Fiesta",
            "Tomar",
            "Pagos",
            "Poema",
            "Artículos",
            "Tecnología",
            "Sueños",
            "Objetivos",
            "Motivación",
            "Música",
            "Naturaleza",
            "Inteligencia artificial",
            "Social",
            "Amor",
            "Romance",
            "Dinero",
            "Amigo",
            "Otro"
        };
    }
}
